name: Code linting

on:
  workflow_call:

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.14"

      - name: Check for unused dependencies
        run: mix deps.get && mix deps.unlock --check-unused

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check for compilation warnings
        run: mix compile --warnings-as-errors