name: Code linting

on:
  workflow_call:
    inputs:
      otp-version:
        required: true
        type: string
      elixir-version:
        required: true
        type: string
      warnings-as-errors:
        default: true
        type: boolean
      check-unused-deps:
        default: true
        type: boolean

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ inputs.otp-version }}
          elixir-version: ${{ inputs.elixir-version }}

      - name: Check formatting
        run: mix do deps.get, format --check-formatted

      - name: Check for unused dependencies
        if: ${{ inputs.check-unused-deps }}
        run: mix deps.unlock --check-unused

      - name: Check for compilation warnings
        if: ${{ inputs.warnings-as-errors }}
        run: mix compile --warnings-as-errors
